[project]
name = "xgboost-with-missing-value"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "xgboost>=2.1.1",
    "matplotlib>=3.9.2",
]
